DEBUG=true
[[ "$DEBUG" = "true" ]] && echo "$(gdate +%s.%N) Running .zprofile..."
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zprofile"
fi
source ~/.profile
