# set the trace prompt to include seconds, nanoseconds, script name and line number
#PS4='+$(date "+%s:%N") %N:%i> '
# save file stderr to file descriptor 3 and redirect stderr (including trace 
# output) to a file with the script's PID as an extension
#exec 3>&2 2>/tmp/startlog.$$
# set options to turn on tracing and expansion of commands contained in the prompt
#setopt xtrace prompt_subst




# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
# enable bash completions for compatibility with Opower scripts
alias shopt=':'
autoload bashcompinit
bashcompinit

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="frosted"
#ZSH_THEME="zanshin"
ZSH_THEME="herbcso"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew bundler rails git ruby gem jira mvn node npm osx python rvm screen sublime svn)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/heroku/bin:/Users/carstendreesbach/.rvm/bin:/Library/Frameworks/GDAL.framework/Programs:/Library/Frameworks/PROJ.framework/Programs:/usr/local/pgsql-9.1/bin:/usr/local/share/python:/usr/local/bin:/Users/carstendreesbach/bin:/Users/carstendreesbach/svnmerge:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/usr/local/sbin:/opt/pose/implementation/bin:/opt/pose/opsqa/bin

zstyle :omz:plugins:ssh-agent id_rsa launchpad-private.ssh

# Set less options
if [[ -x $(which less) ]]
then
  export PAGER="less"
  export LESS="--ignore-case --long-prompt --quiet --chop-long-lines -Sm --RAW-CONTROL-CHARS --quit-if-one-screen --no-init"
  if [[ -x $(which lesspipe.sh) ]]
  then
    LESSOPEN="|lesspipe.sh %s"
    export LESSOPEN
  fi
fi

PATH=$PATH:$HOME/.rvm/bin:/usr/local/share/npm/bin # Add RVM and yeoman to PATH for scripting

# Unified history files across sessions - see http://superuser.com/questions/37576/can-history-files-be-unified-in-bash
# 2011-06-14 decided not to use this after all for now, too annoying to get mixed command history across sessions
export HISTSIZE=1000000 HISTFILESIZE=1000000
#export HISTCONTROL=ignoreboth # remove duplicate history entries
#shopt -s histappend
#PROMPT_COMMAND="$PROMPT_COMMAND;history -a; history -n"
# New history config for supporting huffshell gem https://github.com/paulmars/huffshell
shopt -s histappend
setopt EXTENDED_HISTORY
unalias history # set to fc -l 1 for some reason...?
# setopt hist_expire_dups_first
# setopt hist_ignore_dups # ignore duplication command history list
#shopt hist_ignore_space
shopt -s histverify
#shopt inc_append_history
# setopt share_history # share command history data
setopt APPEND_HISTORY
#setopt HISTORY_VERIFY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
# ignore commands starting with a space
setopt HIST_IGNORE_SPACE

# don't notify on background job completion right away
setopt NO_NOTIFY
# don't annoy coworkers...
setopt NO_BEEP
setopt AUTO_CD
setopt EXTENDED_GLOB

# customizations
function gd() { git diff $* | view -; }
function gdc() { gd --cached $*; }
alias pygrep="grep --include='*.py' $*"
alias rbgrep="grep --include='*.rb' $*"
alias t="script/test $*"
alias f="script/features $*"
alias g="bundle exec guard $*"
alias sr="screen -r"
alias gx="gitx"
alias gxa="gitx --all"
function mcd() { mkdir -p $1 && cd $1 }
function cdf() { cd *$1*/ } # stolen from @topfunky

# load settings common to all shells
source ~/.profile
source ~/bin/dc6_settings.sh
# now reset BLOCKSIZE since '1 doesn't work on Mac
BLOCKSIZE=




# turn off tracing
#unsetopt xtrace
# restore stderr to the value saved in FD 3
#exec 2>&3 3>&-

