# Enable bash completion from homebrew
if [[ -x brew && -f `brew --prefix`/etc/bash_completion ]]; then
  . `brew --prefix`/etc/bash_completion
fi
if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi
if [[ -f ~/.profile ]]; then
  source ~/.profile
fi
if [[ -f "$HOME/.secure" ]]; then
  source "$HOME/.secure"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$HOME/.bin:$PATH"
export workspace="$HOME/opower"
export PATH="/usr/local/bin:$PATH"
export GITHUB_HOST=github.va.opower.it
export POSE_USER=carsten.dreesbach
export GIT_USER=carsten-dreesbach
source $workspace/opower.bash/opower.bash
