# Enable bash completion from homebrew
if [[ -x brew && -f `brew --prefix`/etc/bash_completion ]]; then
  . `brew --prefix`/etc/bash_completion
fi
if [[ -f ~/.bashrc ]]; then
  source ~/.bashrc
fi
if [[ -f ~/.profile ]]; then
  source ~/.profile
fi
if [[ -f "$HOME/.secure" ]]; then
  source "$HOME/.secure"
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
